# Application Configuration (Merged Production + Development)
application:
  name: DevOpsSimulator
  version: 2.0.0-beta   # Using dev version for testing
  environment: development  # Change to 'production' when deploying

server:
  host: 0.0.0.0           # Use 0.0.0.0 for production accessibility
  port: 8080              # Production port
  ssl_enabled: true       # Enable SSL in production
  hot_reload: true        # Useful for development testing

logging:
  level: DEBUG            # Development-friendly logging
  format: json            # Keep JSON format for production
  output: /var/log/app.log # File output for production
  show_stack_trace: true  # Helpful in development

database:
  host: localhost         # Use localhost for dev, change to prod-db.example.com for production
  port: 5432
  name: devops_dev         # Development database name
  # name: devops_prod      # Uncomment for production

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  experimental_features: true

development:
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
