# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 3.0.0-experimental   # use latest version
  environment: development      # or 'testing' / 'production' as needed
  experimental_mode: true

server:
  host: 0.0.0.0
  port: 8080                     # main port for dev/prod
  multi_port: [9000, 9001, 9002] # include experimental ports
  ssl_enabled: true
  hot_reload: true               # useful in development

logging:
  level: TRACE                   # use detailed logging for testing
  format: structured
  output: /var/log/app.log
  show_stack_trace: true
  ai_analysis: enabled

database:
  host: cluster.example.com      # choose experimental cluster
  port: 5432
  name: devops_dev               # or devops_experimental
  distributed: true

features:
  auto_scaling: advanced
  load_balancer: ai-optimized
  backup_enabled: true
  experimental_features: true
  chaos_engineering: enabled

development:
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

ai_features:
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive

notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
